[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unnamed-os.json"

[target.'cfg(target_os = "none")']
runner = "cargo run --package boot --"

[alias]
image = "run -- --no-run"
