[target.'cfg(target_os = "uefi")']
runner = "cargo run --bin boot --package boot --"

[alias]
kbuild = "build --package tyto --target x86_64-unknown-uefi -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem --release"
krun = "run --bin tyto --target x86_64-unknown-uefi -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem --release"
